name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies of the Core
      run: dotnet restore XamaCore
    - name: Restore dependencies of the Win
      run: dotnet restore XamaWinService
    - name: Restore dependencies of the Tests
      run: dotnet restore XamaTests
    - name: Build Core
      run: dotnet build --no-restore XamaCore
    - name: Build Service
      run: dotnet build --no-restore XamaWinService
    - name: Build Tests
      run: dotnet build --no-restore XamaTests
    - name: Test
      run: dotnet test --no-build --verbosity normal XamaTests      

